<<<<<<< HEAD
custom:
  - https://www.buymeacoffee.com/coteschung
  - https://cotes.gitee.io/alipay-wechat-donation
=======
ko_fi: coteschung
custom: https://cotes.gitee.io/alipay-wechat-donation
>>>>>>> 339321defc3aec22b7e4a86af8fffb659a57e5fe
