title:              Isaiah's Blog
email:              isaiahkim1985@gmail.com
description:        test
author:             Isaiah Kim
baseurl:            "/isaiahkim1985.github.io"
url:                "https://isaiahkim1985.github.io"

# Social Profiles
twitter_username:   isaiahkim
github_username:    isaiahkim195
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
